---
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine
    - epel-release

- name: Install required packages
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2


- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  shell: "yum-config-manager --add-repo {{ docker_yum_repo_url }}"


# - name: Add Docker repository.
#   get_url:
#     url: "{{ docker_yum_repo_url }}"
#     dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
#     owner: root
#     group: root
#     mode: 0644

# - name: Configure Docker Edge repo.
#   ini_file:
#     dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
#     section: 'docker-{{ docker_edition }}-edge'
#     option: enabled
#     value: '{{ docker_yum_repo_enable_edge }}'

# - name: Configure Docker Test repo.
#   ini_file:
#     dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
#     section: 'docker-{{ docker_edition }}-test'
#     option: enabled
#     value: '{{ docker_yum_repo_enable_test }}'
